-- Parte 2 NEGA-REVOKE
SELECT USER FROM DUAL;
--ANALISANDO
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE LIKE 'ALUNO';
--REVOGANDO 
REVOKE CREATE VIEW,CREATE PROCEDURE,CREATE SESSION, CREATE TABLE FROM ALUNO;
--CONCEDENDO
GRANT CREATE VIEW,CREATE PROCEDURE,CREATE SESSION, CREATE TABLE TO ALUNO;

--ANALISANDO
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE LIKE 'ALUNO';
--REVOGANDO
REVOKE RESOURCE FROM ALUNO;

--CONCEDENDO
GRANT RESOURCE TO ALUNO;

--ANALISANDO
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE LIKE 'ALUNO';
--
REVOKE UPDATE ON HELP FROM ALUNO;






