
-- INICIA TRANSAÇÃO

-- INSERE REGISTROS
INSERT INTO cadastro VALUES ('Andre','12341244');
SAVEPOINT P1;
INSERT INTO cadastro VALUES ('Joao','12341248');
SAVEPOINT P2;
INSERT INTO cadastro VALUES ('Pedro','12341246');
SAVEPOINT P3;

--ANALISANDO DADOS
SELECT * FROM CADASTRO;

-- RETORNA O TABELA PARA ESTADO ANTERIOR DO BEGIN TRANSACTION
ROLLBACK TO SAVEPOINT P2;


-- EFETIVA AS INFORMACOES NA TABELAS DO BANCO DE DADOS
COMMIT;

-- DELETE FROM cadastro
-- SELECT * FROM CADASTRO
