
--TRIGGER PRA BLOQUEAR USUARIO QUANDO DEMITIDO
CREATE OR REPLACE TRIGGER TG_BLOQUEIA_USUARIO     
    AFTER UPDATE
    OF DATE_DEMISS ON FUNCIONARIO
FOR EACH ROW
BEGIN
    IF (:NEW.DATE_DEMISS IS NOT NULL) THEN
    
        UPDATE USUARIOS SET SITUACAO='B' --BLOQUEIA
		WHERE MATRICULA=:OLD.MATRICULA
        AND COD_EMPRESA=:OLD.COD_EMPRESA;
        
    END IF;
    
END;

--TESTE
SELECT * FROM FUNCIONARIO
WHERE COD_EMPRESA='1'
AND MATRICULA='11';

SELECT * FROM USUARIOS
WHERE COD_EMPRESA='1'
AND MATRICULA='11';
--update teste trigger 
--OBSERVAÇÃO EFETUAR O COMMIT;
UPDATE FUNCIONARIO SET DATE_DEMISS=SYSDATE
WHERE COD_EMPRESA='1'
AND MATRICULA='11';
COMMIT;


SELECT * FROM USUARIOS
WHERE COD_EMPRESA='1'
AND MATRICULA='11';


