
--CRIACAO TRIGGER AUDITA SALARIO
--DROP TRIGGER TG_AUDIT_SAL 
--TRIGGER PARA AUDITAR ALTERACOES DE SALARIO

 
CREATE OR REPLACE TRIGGER TG_AUDIT_SAL
AFTER INSERT OR UPDATE OF SALARIO ON SALARIO 
  FOR EACH ROW

BEGIN
    IF inserting THEN 
     
      INSERT INTO AUDITORIA_SALARIO VALUES 
        (:NEW.COD_EMPRESA,:NEW.MATRICULA,0,:NEW.SALARIO,USER,SYSDATE);
              
      
    ELSIF updating THEN 
      
       INSERT INTO AUDITORIA_SALARIO VALUES 
                   (:NEW.COD_EMPRESA,:NEW.MATRICULA,:OLD.SALARIO,:NEW.SALARIO,USER,SYSDATE);
    
    END IF;
END;


--TESTE
SELECT * FROM AUDITORIA_SALARIO;

UPDATE SALARIO SET SALARIO=SALARIO*1.05
WHERE COD_EMPRESA=1
AND MATRICULA=8;
COMMIT;

