--V_NECCESSIDADES
--ORDEM_PROD,FICHA_TECNICA, ESTOQUE,MATERIAL

CREATE OR REPLACE VIEW V_NECCESSIDADES
   AS
	SELECT A.COD_EMPRESA,
           A.ID_ORDEM,
           A.COD_MAT_PROD,
           A.QTD_PLAN,
           A.QTD_PROD,
	       A.QTD_PLAN-A.QTD_PROD SALDO,
	       B.COD_MAT_NECES,
           D.DESCRICAO,
	       B.QTD_NECES,
	       (A.QTD_PLAN-A.QTD_PROD)*B.QTD_NECES as QTD_REAL_NEC,
	      NVL(C.QTD_SALDO,0) AS QTD_SALDO,
          CASE WHEN  (A.QTD_PLAN-A.QTD_PROD)*B.QTD_NECES>NVL(C.QTD_SALDO,0)
                    THEN 'FALTA ESTOQUE' 
               ELSE 'OK' END MSG
	 FROM ORDEM_PROD A
	 INNER JOIN FICHA_TECNICA B
	 ON A.COD_MAT_PROD=B.COD_MAT_PROD
     AND A.COD_EMPRESA=B.COD_EMPRESA
     
	 LEFT JOIN ESTOQUE C
	 ON B.COD_MAT_NECES=C.COD_MAT
     AND A.COD_EMPRESA=C.COD_EMPRESA
     
	 INNER JOIN MATERIAL D
	 ON B.COD_MAT_NECES=D.COD_MAT
     AND A.COD_EMPRESA=D.COD_EMPRESA
	 WHERE (A.QTD_PLAN-A.QTD_PROD)<>0;
	 
     --TESTE
     SELECT * FROM V_NECCESSIDADES
     WHERE COD_EMPRESA=1
     AND ID_ORDEM=3;
     
     SELECT * FROM FICHA_TECNICA
     WHERE COD_MAT_PROD='1';
	 









