	 
--V_CONTAS_PAGAR
--CONTAS_PAGAR,FORNECEDORES
--SELECT * FROM V_CONTAS_PAGAR

CREATE OR REPLACE VIEW V_CONTAS_PAGAR
AS
SELECT A.COD_EMPRESA,
       A.ID_DOC,
       A.ID_FOR,
       B.RAZAO_FORNEC,
       A.PARC,
       A.DATA_VENC,
       A.DATA_PAGTO,
       A.VALOR,
       CASE WHEN A.DATA_PAGTO IS NULL THEN 'ABERTO' ELSE 'PAGO' END SITUACAO,
       CASE WHEN A.DATA_VENC>SYSDATE THEN 'NORMAL' 
     WHEN A.DATA_PAGTO>A.DATA_VENC   THEN 'PAGTO EF COM ATRASO'
     ELSE 'VENCIDO' END MSG
 FROM CONTAS_PAGAR A
 INNER JOIN FORNECEDORES B
 ON A.ID_FOR=B.ID_FOR
 AND A.COD_EMPRESA=B.COD_EMPRESA;
 
 
 SELECT * FROM V_CONTAS_PAGAR;
 /*
 UPDATE CONTAS_PAGAR SET DATA_PAGTO=SYSDATE
 WHERE ID_DOC='1' AND PARC='1' AND COD_EMPRESA=1;
 */
--V_CONTAS_RECEBER
--CONTAS_RECEBER,CLIENTES
    CREATE OR REPLACE VIEW V_CONTAS_RECEBER
    AS
    SELECT A.COD_EMPRESA, 
           A.ID_DOC,
           A.ID_CLIENTE,
           B.RAZAO_CLIENTE,
           A.PARC,
           A.DATA_VENC,
           A.DATA_PAGTO,
           A.VALOR,
           CASE WHEN A.DATA_PAGTO IS NULL THEN 'ABERTO' ELSE 'PAGO' END SITUACAO,
           CASE WHEN A.DATA_VENC>SYSDATE THEN 'NORMAL' 
                WHEN A.DATA_PAGTO>A.DATA_VENC   THEN 'PAGTO EM COM ATRASO'
                ELSE 'VENCIDO' END MSG,
           CASE WHEN A.DATA_VENC=A.DATA_PAGTO THEN 0
                WHEN A.DATA_PAGTO>A.DATA_VENC THEN CAST(CAST(A.DATA_PAGTO AS DATE)-CAST(A.DATA_VENC AS DATE) AS INT )
                ELSE 
          CAST(SYSDATE-CAST(A.DATA_VENC AS DATE) AS INT ) END DIAS_ATRASO
     FROM CONTAS_RECEBER A
     INNER JOIN CLIENTES B
     ON A.ID_CLIENTE=B.ID_CLIENTE
     AND A.COD_EMPRESA=B.COD_EMPRESA;

 /*
 UPDATE CONTAS_RECEBER SET DATA_PAGTO='05/04/2018'
 WHERE ID_DOC=21 AND PARC=1  AND COD_EMPRESA=1;
 */

SELECT * FROM V_CONTAS_RECEBER;
