--V_CANAL_VENDAS
--CLIENTES,CANAL_VENDAS_G_V,CANAL_VENDAS_V_C


CREATE OR REPLACE  VIEW V_CANAL_VENDAS
AS
SELECT A.COD_EMPRESA,
       A.ID_CLIENTE,
       A.RAZAO_CLIENTE,
       NVL(B.ID_VEND,0)ID_VEND,
       NVL(D.NOME,'SEM CANAL')NOME_VEND,
       NVL(E.ID_GER,0) ID_GER,
       NVL(G.NOME,'SEM CANAL') NOME_GER
       
    FROM CLIENTES A
    LEFT JOIN CANAL_VENDAS_V_C B
    ON A.ID_CLIENTE=B.ID_CLIENTE
    AND A.COD_EMPRESA=B.COD_EMPRESA
    
    LEFT JOIN VENDEDORES C
    ON B.ID_VEND=C.ID_VEND
    AND A.COD_EMPRESA=C.COD_EMPRESA
    
    LEFT JOIN FUNCIONARIO D
    ON C.MATRICULA=D.MATRICULA
    AND A.COD_EMPRESA=D.COD_EMPRESA
    
    LEFT JOIN CANAL_VENDAS_G_V E
    ON B.ID_VEND=E.ID_VEND
    AND A.COD_EMPRESA=E.COD_EMPRESA
    
    LEFT JOIN GERENTES F
    ON E.ID_GER=F.ID_GER
    AND A.COD_EMPRESA=F.COD_EMPRESA
    
    LEFT JOIN FUNCIONARIO G
    ON F.MATRICULA=G.MATRICULA
    AND A.COD_EMPRESA=G.COD_EMPRESA;

-- TESTANDO A VIEW

SELECT * FROM V_CANAL_VENDAS;








