SET SERVEROUTPUT ON
<<BLOCOPRINCIPAL>> --declaracao de label de escopo
DECLARE
V_NUM1 NUMBER := 100;
BEGIN
DECLARE
V_NUM1 NUMBER := 50;
BEGIN
DBMS_OUTPUT.PUT_LINE('Impressão 1 '||BLOCOPRINCIPAL.V_NUM1);
DBMS_OUTPUT.PUT_LINE('Impressão 2 '||V_NUM1);
END;
DBMS_OUTPUT.PUT_LINE('Impressão 3 '||V_NUM1);
END;
/


--outro exemplo
DECLARE V_TEMP NUMBER:=100;
BEGIN
  DBMS_OUTPUT.PUT_LINE(V_TEMP);
  DECLARE V_TEMP NUMBER:=200;
  BEGIN
    DBMS_OUTPUT.PUT_LINE(V_TEMP);
  END;
  DBMS_OUTPUT.PUT_LINE(V_TEMP);
END;
/