-- criando funcao para retornar numero de salarios minimos

CREATE OR REPLACE FUNCTION FN_SAL_MIN (P_SALARIO IN NUMBER)
RETURN NUMBER
    IS
QTD_SAL_MIN NUMBER(10,2);
BEGIN 
    QTD_SAL_MIN:=P_SALARIO/954;
RETURN QTD_SAL_MIN;
END;
/
-- USANDO A FUNCAO,

SELECT A.FIRST_NAME,
       A.SALARY,
       FN_SAL_MIN(A.SALARY) AS QTD_MIN
FROM HR.EMPLOYEES A;

