--OPERADOR DE ADICAO +
SELECT 1+3 AS RESULTADO FROM DUAL;

SELECT a.FIRST_NAME,
       a.SALARY,
       a.SALARY+530 as salario_novo
       FROM HR.EMPLOYEES a;

--OPERADOR DE SUBTRACAO-
SELECT 1-3 AS RESULTADO FROM DUAL;

SELECT 7-4 AS RESULTADO FROM DUAL;

SELECT a.FIRST_NAME,
       a.SALARY,
       a.SALARY-530 as salario_novo
       FROM HR.EMPLOYEES a;

--OPERADOR DE MULTIPLICAO*

SELECT 2*3 AS RESULTADO FROM DUAL;

SELECT 7*4 AS RESULTADO FROM DUAL;


SELECT (7*4)*-1 AS RESULTADO FROM DUAL;


SELECT a.FIRST_NAME,
       a.SALARY,
       a.SALARY*1.10 as salario_novo
       FROM HR.EMPLOYEES a;
       

SELECT a.FIRST_NAME,
       a.SALARY,
       a.SALARY*0.10 as valor_acresc,
       a.SALARY*1.10 as salario_novo
       FROM HR.EMPLOYEES a;

--OPERADOR DE DIVISAO /

SELECT 2/4 AS RESULTADO FROM DUAL;

SELECT 4/2 AS RESULTADO FROM DUAL;

SELECT 7/4 AS RESULTADO FROM DUAL;

SELECT a.FIRST_NAME,
       a.SALARY,
       a.SALARY/10 as salario_novo
       FROM HR.EMPLOYEES a;

--OPERADOR MOD %

SELECT MOD(10,5) AS RESULTADO FROM DUAL;

SELECT MOD(10,3) AS RESULTADO FROM DUAL;

--Exmpressoes 

select 2*4/3+3 from dual;


select ((2*4)/3)+3 from dual;

